apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: urlshortener:latest
        imagePullPolicy: Never  # Ensures Kubernetes uses the locally built image
        ports:
        - containerPort: 5000
        - containerPort: 8000
