apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - name: http-5000
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: http-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
